apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/keycloak/
  - base/agents/weather-agent/
  - base/agents/news-agent/
  - base/agents/fortune-agent/
  - base/agents/traffic-agent/
  - base/agents/email-agent/
  - base/agents/package-agent/
  - base/agents/breakfast-agent/
  - base/agents/assistant/
  - base/dashboard/

commonLabels:
  app: a2a-morning-routine
